name: Deploy Updater

on:
  workflow_call:
    inputs:
      environment:
        description: "GitHub environment name"
        required: true
        type: string
      sst-stage:
        description: "SST deployment stage"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy-updater:
    name: Deploy Updater Service
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
    concurrency:
      group: updater-${{ inputs.environment }}-${{ github.ref }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: '10.4.1'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy Updater
        working-directory: ./apps/updater
        run: pnpm sst deploy --stage ${{ inputs.sst-stage }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_ORGANISATION_ID: ${{ secrets.LINKEDIN_ORGANISATION_ID }}
          LINKEDIN_USER_ID: ${{ secrets.LINKEDIN_USER_ID }}
          QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
          QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}
          QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
          QSTASH_URL: ${{ secrets.QSTASH_URL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          UPDATER_API_TOKEN: ${{ secrets.UPDATER_API_TOKEN }}
          UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
          UPSTASH_EMAIL: ${{ secrets.UPSTASH_EMAIL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}