name: API Deploy (Production)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
    paths:
      - "apps/api/**"

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  run-migrations:
    uses: ./.github/workflows/run-migrations.yml
    with:
      environment: Production
    secrets: inherit

  deploy-api:
    needs: run-migrations
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: Production
      sst-stage: prod
    secrets: inherit
