name: Run Database Migrations

on:
  workflow_call:
    inputs:
      environment:
        description: "GitHub environment name"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  run-migrations:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
    concurrency:
      group: migrations-${{ inputs.environment }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: bun install

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run migrations
        working-directory: ./packages/database
        run: bun migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}